# Setup
title:        Neeraj Bhusare
tagline:      Technology site
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Neeraj Bhusare
  url:        http://nbhusare.github.io

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
